# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5d14e76f6e53aa64e0db073bb32a7c8f0057f43ecfe2c78c97cf52e2af1c5a197ca14e64f6dc1f4983cb5c1a0ba7da59918801bcbb1a49f3fa938f5dfc7f568d

test:
  secret_key_base: 7cea7ab77042bbeeb2f4f49d616818b495014220a7ba736c44e04a7a527632730b5be8ba0102c865f6fffc1d46212fe531d4413186f39fc106f299680fa0e9cd

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
